# Generated by Django 2.2 on 2021-06-08 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_show'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Show',
            new_name='Stock',
        ),
    ]
